package es.unizar.webeng.hello

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

/**
 * Main class generated by default.
 * 
 * [SpringBootApplication] is an annotation, which means aditional metadata with extra information are going to be used
 * by compiler.
 * In this case, it's an alias of 3 annotations:
 *   [EnableAutoConfiguration] allows application to automatically configure the Spring application.
 *   [ComponentScan] allows @Component scan on the package where the application is located.
 *   [Configuration] allows to import additional configuration classes.
 */
@SpringBootApplication
class Application

/**
 * Main application function.
 *
 * Runs the application with the given [args].
 */
fun main(args: Array<String>) {
    /**
     * [runApplication] starts the application with default configuration.
     */
    runApplication<Application>(*args)
}
